# Generated by Django 5.2.6 on 2025-10-17 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('EM_MANUTENCAO', 'Em Manutencao'), ('DESATIVADO', 'Desativado')], default='ATIVO', max_length=60)),
                ('qr_code', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cargo', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('dt_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('foto_user', models.TextField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AGUARDANDO_ATENDIMENTO', 'Aguardando Atendimento'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_ATENDIMENTO', max_length=60)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=60)),
                ('photo', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamado_ativo_FK', to='app.ativo')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamado_usuario_FK', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ManyToManyField(related_name='chamado_funcionario_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('horario', models.TimeField(auto_now_add=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_usuario_FK', to=settings.AUTH_USER_MODEL)),
                ('chamado_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_chamado_FK', to='app.chamado')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=400)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environment_funcionario_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ativo',
            name='environment_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativo_ambiente_FK', to='app.environment'),
        ),
        migrations.CreateModel(
            name='Notificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificate_usuario_FK', to=settings.AUTH_USER_MODEL)),
                ('chamado_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificate_chamado_FK', to='app.chamado')),
            ],
        ),
    ]
