# Generated by Django 5.2.6 on 2025-10-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
