# Generated by Django 5.2.6 on 2025-10-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
