# Generated by Django 5.2.7 on 2025-10-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chamado_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('usuario', 'Usuário'), ('tecnico', 'Técnico')], default='pendente', max_length=20),
        ),
    ]
