# Generated by Django 5.2.7 on 2025-10-30 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='chamado',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='chamado_funcionario_FK', to=settings.AUTH_USER_MODEL),
        ),
    ]
