# Generated by Django 5.2.7 on 2025-11-02 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_ativo_qr_code_alter_chamado_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamado_environment_FK', to='app.environment'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='chamados/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='foto_user',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
