# Generated by Django 5.2.7 on 2025-11-04 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chamado_environment_alter_chamado_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='employee',
        ),
        migrations.AddField(
            model_name='chamado',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to=settings.AUTH_USER_MODEL),
        ),
    ]
