# Generated by Django 5.2.7 on 2025-11-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_users_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
